Hardmode added
indremak/Snake-Game pull request #37
Opened 2020-10-22 20:06 UTC by vaibhavviking

Now there is a hardmode where the controls for the game are inverted. Hardmode can be toggled on/off anytime.

2020-10-23 19:28 UTC, indremak requested changes

2020-10-23 19:28 UTC, indremak commented on index.js
> +var hardmode = 0;
Please change `var` to `let`, use camelCase for variable names.

2020-10-23 19:28 UTC, indremak commented on index.js
> +    if(hardmode==0){
It would be better if  you replace all double equals `==`  with triple equals `===`.

2020-10-23 19:28 UTC, indremak commented on index.js
> +  //  else if (e.keyCode === 82) {
Please don't leave commented out code.

2020-10-24 10:24 UTC, vaibhavviking commented
I have made the required changes. Please review them.

2020-10-25 16:18 UTC, merged